version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
