version: "3"
services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - .:/go/src/server
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
