version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.${ENV}
    env_file:
      - .env
    volumes:
      - ./api:/go/src/api
    environment:
      - PORT=8081
    expose:
      - "8081"
    depends_on:
      - postgres
    restart: on-failure
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.${ENV}
    env_file:
      - .env
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./web:/home/node/app
    expose:
      - "8080"
    depends_on:
      - api
    restart: on-failure
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    expose:
      - "5432"
  proxy:
    image: nginx:alpine
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web
    restart: on-failure

volumes:
  yarn:
