version: "3"
services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile.${ENV:-dev}
    env_file:
      - .env
    volumes:
      - ./api:/go/src/server
    ports:
      - 8081:8081
    depends_on:
      - postgres
    restart: on-failure
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.${ENV:-dev}
    env_file:
      - .env
    volumes:
      - ./web:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - server
    restart: on-failure
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
